-- Primary key table for Core Data entities
CREATE TABLE IF NOT EXISTS Z_PRIMARYKEY (Z_ENT INTEGER PRIMARY KEY, Z_NAME VARCHAR, Z_SUPER INTEGER, Z_MAX INTEGER);

-- School year table
CREATE TABLE IF NOT EXISTS ZYEAR (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZEND TIMESTAMP, ZSTART TIMESTAMP);

-- Semester table
CREATE TABLE IF NOT EXISTS ZSEMESTER (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZTYPEID INTEGER, ZYEAR INTEGER, ZEND TIMESTAMP, ZSTART TIMESTAMP);

CREATE INDEX IF NOT EXISTS ZSEMESTER_ZYEAR_INDEX ON ZSEMESTER (ZYEAR);

-- Subject table
CREATE TABLE IF NOT EXISTS ZSUBJECT (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZNAME VARCHAR);

-- Student table
CREATE TABLE IF NOT EXISTS ZSTUDENT (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZFIRSTNAME VARCHAR, ZLASTNAME VARCHAR);

-- Group table
CREATE TABLE IF NOT EXISTS ZGROUP (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZTYPE INTEGER, ZNAME VARCHAR, ZSORTINGNAME VARCHAR);

-- Course table
CREATE TABLE IF NOT EXISTS ZCOURSE (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZGROUP INTEGER, ZSEMESTER INTEGER, ZSUBJECT INTEGER, ZYEAR INTEGER, ZDAYS BLOB);

CREATE INDEX IF NOT EXISTS ZCOURSE_ZGROUP_INDEX ON ZCOURSE (ZGROUP);

CREATE INDEX IF NOT EXISTS ZCOURSE_ZSEMESTER_INDEX ON ZCOURSE (ZSEMESTER);

CREATE INDEX IF NOT EXISTS ZCOURSE_ZSUBJECT_INDEX ON ZCOURSE (ZSUBJECT);

CREATE INDEX IF NOT EXISTS ZCOURSE_ZYEAR_INDEX ON ZCOURSE (ZYEAR);

-- Performance table
CREATE TABLE IF NOT EXISTS ZPERFORMANCE (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZEDITABLE INTEGER, ZSORTORDER INTEGER, ZTYPE INTEGER, ZCOURSE INTEGER, ZDATE TIMESTAMP, ZWEIGHT FLOAT, ZTITLE VARCHAR);

CREATE INDEX IF NOT EXISTS ZPERFORMANCE_ZCOURSE_INDEX ON ZPERFORMANCE (ZCOURSE);

-- Grade table
CREATE TABLE IF NOT EXISTS ZGRADE (Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZPERFORMANCE INTEGER, ZSTUDENT INTEGER, ZVALUE VARCHAR);

CREATE INDEX IF NOT EXISTS ZGRADE_ZPERFORMANCE_INDEX ON ZGRADE (ZPERFORMANCE);

CREATE INDEX IF NOT EXISTS ZGRADE_ZSTUDENT_INDEX ON ZGRADE (ZSTUDENT);

-- One grade per student per performance (natural key)
CREATE UNIQUE INDEX IF NOT EXISTS idx_zgrade_performance_student_unique ON ZGRADE (ZPERFORMANCE, ZSTUDENT);

-- Map courses to students
CREATE TABLE IF NOT EXISTS Z_1STUDENTS (Z_1COURSES INTEGER, Z_6STUDENTS INTEGER, PRIMARY KEY (Z_1COURSES, Z_6STUDENTS));

CREATE INDEX IF NOT EXISTS Z_1STUDENTS_Z_6STUDENTS_INDEX ON Z_1STUDENTS (Z_6STUDENTS, Z_1COURSES);

-- Map groups to semesters
CREATE TABLE IF NOT EXISTS Z_3SEMESTERS (Z_3GROUPS INTEGER, Z_5SEMESTERS INTEGER, PRIMARY KEY (Z_3GROUPS, Z_5SEMESTERS));

CREATE INDEX IF NOT EXISTS Z_3SEMESTERS_Z_5SEMESTERS_INDEX ON Z_3SEMESTERS (Z_5SEMESTERS, Z_3GROUPS);

-- Map groups to students
CREATE TABLE IF NOT EXISTS Z_3STUDENTS (Z_3GROUPS2 INTEGER, Z_6STUDENTS1 INTEGER, PRIMARY KEY (Z_3GROUPS2, Z_6STUDENTS1));

CREATE INDEX IF NOT EXISTS Z_3STUDENTS_Z_6STUDENTS1_INDEX ON Z_3STUDENTS (Z_6STUDENTS1, Z_3GROUPS2);

-- Map groups to school years
CREATE TABLE IF NOT EXISTS Z_3YEARS (Z_3GROUPS1 INTEGER, Z_8YEARS INTEGER, PRIMARY KEY (Z_3GROUPS1, Z_8YEARS));

CREATE INDEX IF NOT EXISTS Z_3YEARS_Z_8YEARS_INDEX ON Z_3YEARS (Z_8YEARS, Z_3GROUPS1);

-- Map students to school years
CREATE TABLE IF NOT EXISTS Z_6YEARS (Z_6STUDENTS2 INTEGER, Z_8YEARS1 INTEGER, PRIMARY KEY (Z_6STUDENTS2, Z_8YEARS1));

CREATE INDEX IF NOT EXISTS Z_6YEARS_Z_8YEARS1_INDEX ON Z_6YEARS (Z_8YEARS1, Z_6STUDENTS2);

-- Map subjects to school years
CREATE TABLE IF NOT EXISTS Z_7YEARS (Z_7SUBJECTS INTEGER, Z_8YEARS2 INTEGER, PRIMARY KEY (Z_7SUBJECTS, Z_8YEARS2));

CREATE INDEX IF NOT EXISTS Z_7YEARS_Z_8YEARS2_INDEX ON Z_7YEARS (Z_8YEARS2, Z_7SUBJECTS);

INSERT INTO
    Z_PRIMARYKEY (Z_ENT, Z_NAME, Z_SUPER, Z_MAX)
VALUES
    (1, 'Course', 0, 0),
    (2, 'Grade', 0, 0),
    (3, 'Group', 0, 0),
    (4, 'Performance', 0, 0),
    (5, 'Semester', 0, 0),
    (6, 'Student', 0, 0),
    (7, 'Subject', 0, 0),
    (8, 'Year', 0, 0);
